generation:
  backend: unsloth
  input_path: /home/xchen6/breaking_updates_rl/analysis/data/full_data_without_none.json
  output_base_dir: /home/xchen6/breaking_updates_rl/experiments/model_selection
  model_id: allenai/Olmo-3-7B-Instruct
  max_seq_length: 35000
  max_input_tokens: 32000
  max_new_tokens: 4000
  load_in_4bit: true
  load_in_8bit: false
  full_finetuning: false
  temperature: 0.2

evaluation:
  backend: container_patcher
  input_path: /home/xchen6/breaking_updates_rl/experiments/model_selection/allenai/Olmo-3-7B-Instruct_20260318-105317
  run_tests: true
  stats_filename: overall_statistics_new.json

  